name = "resettle-development-service-intelligence"
main = "./src/index.ts"
workers_dev = true
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = ""
localConnectionString = "postgresql://resettler:password@localhost:5432/resettle_intelligence"

[placement]
mode = "smart"

[observability]
enabled = true
