name = "resettle-staging-service-intelligence"
main = "./src/index.ts"
minify = true
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "4deace14f00440c99e056a06cb456b8b"

[placement]
mode = "smart"

[observability]
enabled = true

[limits]
cpu_ms = 5000
